#!/bin/bash

# Restart Polybar per monitor
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 0.1; done
for m in $(polybar --list-monitors 2>/dev/null | cut -d: -f1); do
	MONITOR=$m polybar main &
done
