#!/bin/bash

win=$(xdotool getactivewindow)
pid=$(xprop -id "$win" _NET_WM_PID 2>/dev/null | awk '{print $3}')
class=$(xprop -id "$win" WM_CLASS 2>/dev/null | awk -F'"' '{print $2}')

if [[ "$class" == *"Alacritty"* ]] || [[ "$class" == *"org.dwm"* ]]; then
  shell_pid=$(pgrep -P "$pid" 2>/dev/null | tail -n1)
  if [[ -n $shell_pid ]]; then
    cwd=$(readlink -f "/proc/$shell_pid/cwd" 2>/dev/null)
    shell=$(readlink -f "/proc/$shell_pid/exe" 2>/dev/null)
    if grep -qs "$shell" /etc/shells 2>/dev/null && [[ -d $cwd ]]; then
      echo "$cwd"
      exit 0
    fi
  fi
fi
echo "$HOME"
