#!/bin/bash

PIP_WIDTH=600
PIP_HEIGHT=338
MARGIN_RIGHT=40
MARGIN_TOP_PCT=4

while true; do
  read -r monitor_w monitor_h < <(xrandr --current 2>/dev/null | awk '
    / connected/ {
      for (i = 1; i <= NF; i++) {
        if ($i ~ /^[0-9]+x[0-9]+[+-]/) {
          split($i, a, /[x+]/)
          print a[1], a[2]
          exit
        }
      }
    }')
  monitor_w=${monitor_w:-2560}
  monitor_h=${monitor_h:-1440}

  wid=$(xdotool search --sync --name "Picture-in-Picture" 2>/dev/null | tail -1)
  [[ -z "$wid" ]] && continue
  xdotool windowsize "$wid" "$PIP_WIDTH" "$PIP_HEIGHT" 2>/dev/null
  xdotool windowmove "$wid" $((monitor_w - PIP_WIDTH - MARGIN_RIGHT)) $((monitor_h * MARGIN_TOP_PCT / 100)) 2>/dev/null
  sleep 0.5
done
