include-file = ~/.local/share/dwm/themes/current/polybar.ini

[bar/main]
monitor = ${env:MONITOR:}

height = 35

padding-top = 10
padding-bottom = 10
padding-left = 2
padding-right = 2
module-margin = 1

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = JetBrainsMono Nerd Font:size=14;2

modules-left = dwm dwm-tags
modules-center = clock combined
modules-right = tray bluetooth network pulseaudio brightness cpu lock battery

cursor-click = pointer
cursor-scroll = ns-resize

; --- left ---

[module/dwm]
type = custom/text
format = 
click-left = dwm-launch-menu
click-right = dwm-launch-menu drun

[module/dwm-tags]
type = custom/script
exec = ~/.local/share/dwm/scripts/polybar/dwm-tags.sh
tail = true

; --- center ---

[module/clock]
type = internal/date
interval = 1
time = "%I:%M %p"
label = %{A3:dwm-launch-terminal:}%time%%{A}

[module/combined]
type = custom/script
exec = ~/.local/share/dwm/scripts/polybar/indicators/combined.sh
tail = true

; --- right ---

[module/tray]
type = internal/tray
tray-spacing = 6px
tray-size = 55%

[module/bluetooth]
type = custom/script
exec = ~/.local/share/dwm/scripts/polybar/indicators/bluetooth.sh
tail = true
click-left = dwm-launch-bluetooth

[module/network]
type = internal/network
interface-type = wireless
interval = 3
format-connected = %{A1:dwm-launch-wifi:}<ramp-signal>%{A}
format-disconnected = %{A1:dwm-launch-wifi:}<label-disconnected>%{A}
label-disconnected = 󰤮
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

[module/pulseaudio]
type = internal/pulseaudio
format-volume = %{A1:dwm-launch-audio:}%{A3:pamixer -t:}<ramp-volume>%{A}%{A}
format-muted = %{A1:dwm-launch-audio:}%{A3:pamixer -t:}<label-muted>%{A}%{A}
label-muted = 
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/brightness]
type = internal/backlight
card = nvidia_wmi_ec_backlight

format = %{A1:brightnessctl set +5%:}%{A3:brightnessctl set 5%-:}<ramp>%{A}%{A}

ramp-0 = 󰃞
ramp-1 = 󰃟
ramp-2 = 󰃠

[module/cpu]
type = internal/cpu
format = %{A1:dwm-launch-btop:}<label>%{A}
label = 󰍛

[module/lock]
type = custom/script
exec = echo "󰌾"
click-left = dwm-lock-screen

[module/battery]
type = custom/script
exec = ~/.local/share/dwm/scripts/polybar/indicators/battery.sh
interval = 2
